config/routes.rb
Rails.application.routes.draw do
  root :to => "products#index"
  resources :products
  resource :cart, only: [:show]
  resources :orders
  resources :order_items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :products, through: :order_items
  before_save :update_total
  before_create :update_status

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil?
      self.status = "In progress"
    end
  end

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items
  validates :name, :presence => true
  validates :price, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    @item = @order.order_items.new(item_params)
    @order.save
    session[:order_id] = @order.id
    redirect_to products_path
  end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    @order.save
    redirect_to cart_path
  end

private

  def item_params
    params.require(:order_item).permit(:quantity, :product_id, :image_tag)
  end
end

app/controllers/orders_controllers.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to orders_path
    else
      render :new
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order= Order.find(params[:id])

    if @order.update(order_params)
      redirect_to order_path
    else
      render :edit
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  private
  def order_params
    params.require(:order).permit(:status, :total_price)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_params, only: [:show,:edit,:update,:destroy]
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def show
  end

  def new
    respond_to do |format|
      format.html { redirect_to products_path }
      format.js
    end
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    pokemon_image_tag = Pokemonapi.new(@product.image_tag)
    @product.image_tag = pokemon_image_tag.set_pokemon
    if @product.save
      respond_to do |format|
        format.html { redirect_to products_path }
        format.js
      end
    else
      render :new
    end
  end

  def edit
    respond_to do |format|
      format.html { redirect_to product_path }
      format.js
    end
  end

  def update
    if @product.update(product_params)
      pokemon_image_tag = Pokemonapi.new(@product.image_tag)
      @product.image_tag = pokemon_image_tag.set_pokemon
      @product.save
      respond_to do |format|
        format.html { redirect_to product_path }
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    @products = Product.all
    respond_to do |format|
      format.html { redirect_to products_path }
      format.js
    end
  end

  private

  def find_params
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :image_tag)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<% if @order_items.any? %>
  <% @order_items.each do |item| %>
    <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"}, remote: true %></p>
    <p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %> | Photo: <%= image_tag item.image_tag %> </p>
  <% end %>
  <hr>
  <p>Your Total: <%= number_to_currency current_order.total_price %></p>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>

<p><%= link_to "Return to products", products_path, class: "btn btn-warning" %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VermilionBazaar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="card_display_ID">
      <h3><%= link_to "Cart", cart_path, class: "btn btn-info" %></h3>
    </div>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= render "layouts/errors", :object => @order %>

<%= form_for @order do |f| %>
  <%= f.label :status %>
  <%= f.text_field :status %>
  <hr>
  <%= f.label :total_price %>
  <%= f.number_field :total_price %>
  <hr>
  <%= f.submit %>
<% end %>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product, remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <hr>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <hr>
  <%= f.label :image_tag%>
  <%= f.number_field :image_tag  %>
  <hr>
  <%= f.submit %>
<% end %>

app/views/products/_order_item_form.html.erb
<%= form_for @order_item, remote: true do |f| %>
  <%= f.hidden_field :product_id, value: product.id %>
  <%= f.hidden_field :image_tag, value: product.image_tag %>
  <%= f.number_field :quantity %>
  <%= f.submit "Add to cart", class: "btn btn-info" %>
<% end %>

app/views/products/_product.html.erb
<div class="card_product" id="annie<%= product.id %>">
  <p><%= product.name %> | <%= number_to_currency product.price %></p>
  <% if product.image_tag != nil %>
    <p><%= image_tag product.image_tag %></p>
  <% end %>
  <%= link_to "Delete", product_path(product), :data => {:confirm => "You sure?", :method => "delete"}, remote: true, class: "btn btn-danger" %>
     <p><%= link_to "Edit", edit_product_path(product), class: "btn btn-warning", remote: true %></p>

     <%= form_for @order_item, remote: true do |f| %>
       <%= f.hidden_field :product_id, value: product.id %>
       <%= f.hidden_field :image_tag, value: product.image_tag %>
       <%= f.number_field :quantity %>
       <%= f.submit "Add to cart", class: "btn btn-info" %>
     <% end %>

</div>

app/views/products/create.js.erb
$('form').remove();
$('#ajax_new_card').show();
$('#new_cards').prepend('<%= j render(@product) %>');

app/views/products/destroy.js.erb
$('#annie<%= @product.id %>').remove();

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "layouts/errors", :object => @product %>

<%= render "form" %>

<p><%= link_to "Return to product", product_path %></p>

app/views/products/edit.js.erb
$('#ajax_new_card').hide().after('<%= j render("form") %>')

app/views/products/index.html.erb
<div class="container">

  <div class="jumbotron">
    <h1>Pokemon Bazaar</h1>
  </div>
  <hr>
  <p><%= link_to "Add a new card", new_product_path, id: "ajax_new_card", class: "btn btn-primary", remote: true %></p>
  <hr>
  <div class="cards" id="new_cards">
     <% @products.each do |product| %>

       <%= render product %>


    <% end %>


  </div>

</div>

app/views/products/new.html.erb
<h1>Add New Product Information</h1>

<%= render "products/form" %>

<p><%= link_to "Return to Products", products_path %></p>

app/views/products/new.js.erb
$('#ajax_new_card').hide().after('<%= j render("form") %>')

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

  <h4>Price: $<%= @product.price %></h4>
  <p><%= link_to "Edit", edit_product_path(@product) %></p>
  <p><%= link_to "Delete", product_path(@product), class: "btn btn-info",
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to Products", products_path %></p>

app/views/products/update.js.erb
$('form').remove();
$('#annie<%= @product.id %>').hide();
$('#ajax_new_card').show();
$('#new_cards').prepend('<%= j render(@product) %>');